config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :logs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log <ApplicationRecord  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
 def index
      @log = Log.new()
      @logs = Log.order(date: :desc)
      @total_calorie_breakfast = breakfast_calorie
      @total_calorie_lunch = lunch_calorie
      @total_calorie_dinner = dinner_calorie
  end
  
  def create
     l= Log.new(params[:log].permit(:date, :category, :name, :servings, :calories_per_serving))
      l.save
      redirect_to logs_url
  end
  
  
  def edit
    l = Log.find(params[:id])
    @logs = Log.order(date: :desc)
    @log = l
    render 'index'
  end
  

  def update
      l = Log.find(params[:id])
      l.update(params[:log].permit(:date, :category, :name, :servings, :calories_per_serving))
      redirect_to logs_url
  end
  
  def destroy
      l = Log.find(params[:id])
      l.destroy
      redirect_to logs_url
  end
  
  def breakfast_calorie
        t=0
        @logs.each do |i|
            if i.category == 'Breakfast'
                t += (i.servings * i.calories_per_serving)
            end
            
        end
        return t
    end
    
  def lunch_calorie
        t = 0
        @logs.each do |i|
            if i.category == 'Lunch'
               t += (i.servings * i.calories_per_serving)
            end
        end
        return t
    end

  def dinner_calorie
        t =0
        @logs.each do |i|
            if i.category == 'Dinner'
               t += (i.servings * i.calories_per_serving)
            end
        
        end
        return t
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fooddiary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logs/index.html.erb
<h1>Track Calories</h1>
<%= form_with(model: @log, local: true) do |form| %>
    <div class="field">
        <%= form.label :date %>
        <%= form.text_field :date, id: :log_date %>
    </div>

    <div class = "field">
        <%=form.label :category %>
        <%=form.select(:category, id: :log_category) do %>
            <%['Breakfast', 'Lunch', 'Dinner'].each do |cat| %>
                <%=content_tag(:option, cat, value: cat, selected: @log.category == cat)%>
            <% end %>
        <%end%>

    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :log_name %>
    </div>

    <div class="field">
        <%= form.label :servings %>
        <%= form.number_field :servings, id: :log_servings %>
    </div>

    <div class="field">
        <%= form.label :calories_per_serving %>
        <%= form.number_field :calories_per_serving, id: :log_calories_per_serving %>
    </div>

        
    </div>

    <div class="field">
        <%= form.submit %>
    </div>
<% end %>


<table>
    <thead>
        <tr>
            <th>Delete</th>
            <th>Update</th>
            <th>date</th>
            <th>category</th>
            <th>name</th>
            <th>#servings</th>
            <th>#calories_per_serving</th>
            <th>Total Calories</th>
            
        </tr>
    </thead>

    <tbody>
        <% @logs.each do |t| %>
            <tr>
                <td>
                    <%=link_to(t, method: :delete) do %>
                        <img width= "35" height ="35" src="/trashcan.png" />
                    <% end %>
                </td>
                <td>
                    <%=link_to('edit', edit_log_path(t)) %>
                </td>
                <td><%= t.date %></td>
                <td><%= t.category %></td>
                <td><%= t.name %></td>
                <td><%= t.servings %></td>
                <td><%= t.calories_per_serving %></td>
                <td><%= t.servings * t.calories_per_serving %></td>
            </tr>
        <% end %>
    </tbody>
</table>



<h1>Total Calories</h1>
<p>Total Breakfast: <%=@total_calorie_breakfast %></p>
<p>Total Lunch: <%= @total_calorie_lunch %></p>
<p>Total Dinner: <%= @total_calorie_dinner %></p>